# Generated by Django 3.2.9 on 2021-11-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_api'),
    ]

    operations = [
        migrations.DeleteModel(
            name='API',
        ),
    ]
