# Generated by Django 3.2.9 on 2021-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lacre', models.FloatField(max_length=10)),
                ('nome', models.CharField(max_length=30)),
                ('datapedido', models.FloatField(max_length=10)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
