# Generated by Django 3.2.9 on 2021-11-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
