# Generated by Django 3.2.9 on 2021-11-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=36)),
                ('cidade', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='API',
        ),
    ]
